// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrdbifeuvxsdxcaqssan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyZGJpZmV1dnhzZHhjYXFzc2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzAwODksImV4cCI6MjA3MjQ0NjA4OX0.UKVDWhSw_lX4Is6mewRkpPmwADom7Jx0aVNkPB-Akxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});